[package]
name = "maintask"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
arrayref = "0.3.8"
concrete-fft = "0.4.1"
dyn-stack = "0.9.1"
num-traits = "0.2.19"
